---
abstract: 'Lightweight field hash for inside-out objects'
author:
  - 'Fuji, Goro (gfx) <gfuji(at)cpan.org>.'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  Test::LeakTrace: 0.07
  Test::More: 0.62
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Hash::FieldHash
name: Hash-FieldHash
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  XSLoader: 0.02
  parent: 0.221
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-Hash-FieldHash.git
version: 0.11
